name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    env:
      AUTHOR_TESTING: 1
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
        perl: [ '5' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        if: runner.os != 'Windows'
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Set up perl
        if: runner.os == 'Windows'
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: 'strawberry'
      - run: perl -V
      - name: Install Perl deps
        run: |
          cpanm --verbose --notest --installdeps .
      - name: Install Perl author deps
        run: |
          cpanm --notest --installdeps --with-develop .
      - name: Run tests
        run: |
          cpanm --verbose --test-only .
